def foo []: nothing -> list<record<id: string, title?: string, all_titles: list<record<language: string, title: string>>, description: record, links: list<string>, is_locked: bool, original_language?: string, last_volume?: string, last_chapter?: string, publication_demographic?: string, status?: string, year?: int, content_rating?: string, tags: list<record<id: string, name: string, group: string>>, state?: string, chapter_numbers_reset_on_new_volume: bool, created_at?: datetime, updated_at?: datetime, version?: int, available_translated_languages: list<string>, last_uploaded_chapter?: string, rels: list<record<id: string, type: string, related?: string, attributes?: record>>>> {
  #                              ^ type.enum
  #                                ^ variable.parameter
  #                                  ^ punctuation.special
  #                                      ^ type
  #                                                                                                                                                                                                                                                                                                                                                          ^ type
  #                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ^ variable.parameter
  #                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ^ type
  return []
}
