name: CI

on:
  push:
    branches: [main]
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2
      - name: Set up examples
        shell: bash
        run: |-
          git clone https://github.com/nushell/nu_scripts examples/nu_scripts -q --single-branch --depth=1
      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
        with:
          generate: false
          test-rust: true
          test-node: true
          test-python: true
          test-go: true
          test-swift: false
      - name: Parse examples
        uses: tree-sitter/parse-action@v4
        with:
          files: |-
            examples/nu_scripts/**/*.nu
          invalid-files-list: script/known-failures.txt
